BUNDLE_IDENTIFIER ="com.4js.crypto"
APPNAME           ="Crypto"
BUILD_FGL         = yes
USER_EXTENSION_SRCS = crypto.m
#TARGET=phone
MODE=debug

include $(shell echo $${FGLDIR// /\\ })/lib/Makefile-gmi
#PROVISIONING_PROFILE=/Users/leo/Library/MobileDevice/Provisioning\ Profiles/1bc0e661-d09d-4727-ac24-9de63d8fc852.mobileprovision
#IDENTITY="iPhone Distributon: FourJ's Development Tools Labs GmbH" 
