IMPORT util

GLOBALS
    CONSTANT URL = "http://121.40.207.50:3000"
    #CONSTANT URL = "http://10.40.40.18/wt10dev/ws/r/awsp920"
    #CONSTANT UPDATE_URL="http://10.40.61.22:8080/app/release.json"
    CONSTANT UPDATE_URL="http://10.40.41.72:8080/app/release.json"
    CONSTANT TIMEOUT=30
    CONSTANT IP = 'androidstore.oss-cn-hangzhou.aliyuncs.com'
    CONSTANT PORT = '80'
    CONSTANT PROJECT = 'rainbow'
    DEFINE ordernum INTEGER
END GLOBALS